### ISSUE TITLE
bug: 表格中ID项的宽度没必要太窄

### ISSUE THREAD

**Issue by jeak01** [APIParkLab/APIPark#107]
### Current Behavior

所有服务、消费者、团队等菜单中，ID字段的宽度没必要太窄。右侧很多空间，并且这个表格宽度也无法拖动调整。
![image](https://github.com/user-attachments/assets/073482bb-9990-4f8e-83a7-08669db11043)

### Steps to Reproduce

1. 使用DEMO的访客模式
2.点击左侧服务菜单即可看到右侧的宽度问题

### Environment

- APINTO Dashboard version (run `apinto dashboard version`):
- Operating system (run `uname -a`):
- 使用Chorme浏览器
- 使用比较大尺寸的屏幕

**Comment by Dot-Liu** [comment]
感谢您的反馈。  ID用作唯一标志，其值由程序自动生成，一般在调用openAPI时才有意义
因此，我们提供复制操作，帮助使用者快速复制。该值对于人类来说是不可读且没太大意义，因此没必要显示完全。
设计如此，不是bug。
