### ISSUE TITLE
help request: Streaming support

### ISSUE THREAD

**Issue by benone** [APIParkLab/APIPark#133]
### Description

Hi! Does APIPark support streaming API? https://platform.openai.com/docs/api-reference/streaming
If not It will be great feature.

### Environment

- APIPark version:
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
At present, it is not supported. Why is it a good feature if it is not available?
The AI typewriter mode is still very popular nowadays, and its implementation is based on streaming data transmission.

**Comment by HaloXie** [comment]
请问，是否有确切的 stream 接口功能排期？另外现在支持 assitant 模式吗

**Comment by benone** [comment]
@Dot-Liu Thank you! I build AI chat and streaming is good UI practice for users.
