### ISSUE TITLE
bug: 加完AI模型后，一个都没有调用成功

### ISSUE THREAD

**Issue by pt-cc** [APIParkLab/APIPark#142]
### Current Behavior

 加完AI模型后，一个都没有调用成功。

### Environment

docker 最新版，1.2 beta

**Comment by pt-cc** [comment]
有没有调用成功的，给个示例，最基本的openai就行

**Comment by rolealiu** [comment]
> ### Current Behavior
> 加完AI模型后，一个都没有调用成功。
> 
> ### Expected Behavior
> _No response_
> 
> ### Error Logs
> _No response_
> 
> ### Steps to Reproduce
> _No response_
> 
> ### Environment
> docker 最新版，1.2 beta

你是否已经配置好了模型的token或者其他必要的鉴权？APIPark只负责AI API的接入，但不提供免费的AI API调用。

你可以查看以下教程中的配置模型供应商部分的内容：
https://docs.apipark.com/zh-Hans/docs/services/ai_services

如果你已经配置好了token但依然无法调用，可以将你的配置信息截图并且隐藏关键信息，我们会再帮你排查。

**Comment by pt-cc** [comment]
感谢解答。

apipark 配置
![image](https://github.com/user-attachments/assets/c64ca8d4-1f3d-4c69-9a1a-4bc2049a9618)


我使用 脚本调用 aws bedrock是通的，下面是配置
![image](https://github.com/user-attachments/assets/1fad07ca-e1f2-4485-8c95-68e9bd4a0155)
![image](https://github.com/user-attachments/assets/428286ea-4cd1-4244-a283-3556ffdd9f8e)
已经发布并订阅
![image](https://github.com/user-attachments/assets/f0b58a66-a1ea-4d79-9a64-f671cd04b5fb)
调用失败
<img width="981" alt="image" src="https://github.com/user-attachments/assets/234ee5c7-9be9-4881-9a51-d0d9d8b73323">

另外 openapi 配置
![image](https://github.com/user-attachments/assets/b05ff676-0b10-4361-8748-2ac7accfaa78)
![image](https://github.com/user-attachments/assets/25f47604-1acc-455b-8954-8ca8bfbbd0b1)
调用失败
<img width="970" alt="image" src="https://github.com/user-attachments/assets/d09c2834-19e1-4943-a37e-a388525442ea">

**Comment by Dot-Liu** [comment]
关于openai，你是在国内的服务器访问吗？如果是，那需要走个代理
此处的open_api_base需要填写为：https://api.openai-proxy.com

**Comment by pt-cc** [comment]
server 端在国外的

**Comment by Dot-Liu** [comment]
麻烦尝试下在server端使用curl访问https://api.open.com/v1/chat/completions，看看是否能够访问

**Comment by pt-cc** [comment]
上面的url是不是错了，https://api.openai.com/v1/chat/completions
![image](https://github.com/user-attachments/assets/e763abfd-45e2-4aaa-889d-da00bdfcc49f)

**Comment by Dot-Liu** [comment]
稍等，我先尝试复现看看

**Comment by pt-cc** [comment]
![image](https://github.com/user-attachments/assets/4d0b18f0-f261-4c2c-88f4-6cf09860f29b)
我是把 https://github.com/APIParkLab/APIPark/blob/main/scripts/docker-compose.yml 拆分开部署的

**Comment by Dot-Liu** [comment]
我们这边已经复现了这两个bug，感谢反馈，我们先查一下具体原因
bedrock有可能是签名方式做了改变，我们先确定看看，感谢反馈

**Comment by pt-cc** [comment]
@Dot-Liu  请问1.3-beta 版本有解决上述问题吗？

**Comment by Dot-Liu** [comment]
您好，这个问题应该是[Apinto](https://github.com/eolinker/apinto)节点的问题，预计今明两天内会修复并发板

**Comment by pt-cc** [comment]
好滴

**Comment by Dot-Liu** [comment]
久等了，请将apipark更新到1.3.1-beta，并将apinto更新到0.19.3
更新方法如下：
先执行`quick-start.sh`脚本
```
curl -sSO https://download.apipark.com/install/quick-start.sh; bash quick-start.sh
```
安装APIPark，如下图：
![image](https://github.com/user-attachments/assets/cc5e815f-daba-481e-8998-0227f7d1dc79)
由于mysql、redis、influxdb不需要重新部署，因此我选择了`no`
![image](https://github.com/user-attachments/assets/534e7959-fbde-408f-b76e-351d494169f2)
重新下载部署Apipark
![image](https://github.com/user-attachments/assets/6575b556-f1ca-487e-827c-67fb12aeeef7)
重新下载部署Apinto
![image](https://github.com/user-attachments/assets/19ac6535-fb9e-449b-8e2b-cb83bd16db25)
