### ISSUE TITLE
help request: 你们好，我调用api不知道为什么一直提示403，我明明进行订阅了也携带token进行请求了

### ISSUE THREAD

**Issue by zhangdehuiaixuexi** [APIParkLab/APIPark#151]
### Description

![image](https://github.com/user-attachments/assets/2cef2c08-0b7f-46aa-a3ca-e9bfe7cd22c8)
![image](https://github.com/user-attachments/assets/4dace37a-5288-4b09-b6bb-ab4a8a1a57f9)
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/c37e076f-a1fa-42e1-b9e3-2f2d899986c6" />
![image](https://github.com/user-attachments/assets/2575f44f-4d7f-4c12-a7c2-b4d56b19acbe)
以上是我的配置，弄了很久都不知道为什么一直提示403，不好意思麻烦你们了

### Environment

- APIPark version: 1.3
- Operating system (run `uname -a`): Linux lx.dev.server 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
使用docker-compose部署的

**Comment by Dot-Liu** [comment]
你请求的时候路径有问题，应该填/products/xxx，根据路由的信息/products/*是前缀

**Comment by Dot-Liu** [comment]
我这里指的是，你访问的时候，路径应该填`/products/xxx`，路由的信息是进行前缀匹配，因此可以匹配以`/products/`为前缀的所有API

**Comment by zhangdehuiaixuexi** [comment]
好的已经可以了，不好意思麻烦您了，谢谢你的帮助，万分感谢，祝你生活愉快😁。我调试的时候一直提示403，所以我一直以为是我权限问题，所以没关注路径问题，因为在我的印象中一般路径问题应该出现404🤔。

**Comment by Dot-Liu** [comment]
感谢您的支持～
