### ISSUE TITLE
bug: 新增发布系统报错

### ISSUE THREAD

**Issue by yingjoumong8** [APIParkLab/APIPark#38]
### Current Behavior

![image](https://github.com/user-attachments/assets/6db06b6c-5c76-4261-bf89-837fe424489a)

### Steps to Reproduce

1

### Environment

- APINTO Dashboard version (run `apinto dashboard version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
您看看API文档和服务文档是否创建了

**Comment by Dot-Liu** [comment]
该问题已经复现，感谢您的反馈
原因是API文档和服务文档在发布前需要创建，以便在服务广场中展示，我们优化一下提示

**Comment by yingjoumong8** [comment]
好的，已解决
