### ISSUE TITLE
bug:用户页面，表格文字没有上下居中

### ISSUE THREAD

**Issue by riverLethe** [APIParkLab/APIPark#4]
### Current Behavior

在用户页面，表格上的文字没有上下居中，展示错位
![img_v3_02dt_c1851bac-e50d-4b08-ba7c-5f7b08c4d81g](https://github.com/user-attachments/assets/c74d7faf-4655-4098-9a46-e949384eb46b)

### Steps to Reproduce

无

### Environment

DEMO 环境，https://demo.apipark.com/member/list

**Comment by rolealiu** [comment]
新版本已经修复，感谢反馈👍
