### ISSUE TITLE
bug: 管理员 Admin 登录，新增成员后，提示“暂无编辑权限，请联系管理员分配。”

### ISSUE THREAD

**Issue by snycloud** [APIParkLab/APIPark#42]
### Current Behavior

![image](https://github.com/user-attachments/assets/6b4c811a-5e8e-470a-b16f-0746a987d0a7)

### Steps to Reproduce

管理员 Admin 登录，新增成员后，提示“暂无编辑权限，请联系管理员分配。”

### Environment

- APINTO Dashboard version (run `apinto dashboard version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
好的，目前已复现，我们尽快修复

**Comment by snycloud** [comment]
![image](https://github.com/user-attachments/assets/9bbea47e-f7a4-436b-91b5-54389c1cacf6)
添加服务也会出现 403

**Comment by Dot-Liu** [comment]
噢，添加服务之前需要先添加团队，您看看团队是否没创建

**Comment by snycloud** [comment]
![image](https://github.com/user-attachments/assets/a5d6af70-ce0d-4017-a11c-273265ad5479)
团队都添加了，而且添加服务的时候团队也是可以选择到的，也是在admin的登录态下操作的

**Comment by snycloud** [comment]
![image](https://github.com/user-attachments/assets/1fdfd6ba-fa07-4641-888c-bd7d2594438e)

**Comment by Dot-Liu** [comment]
目前是admin登录吗？我这边没有复现出来呢

**Comment by snycloud** [comment]
是 Admin 登录的

**Comment by snycloud** [comment]
是 Admin 登录的
![image](https://github.com/user-attachments/assets/5dbb8fd3-1a6e-48f9-89f1-1c2ba9a30d31)

添加服务，点击提交没反应
![image](https://github.com/user-attachments/assets/9de0fde3-406e-414a-96f8-11e3a92f4814)

**Comment by snycloud** [comment]
以下是部署流程：
-----------------------------------------------
-----------------------------------------------



[root@centos home]# ./quick-start.sh
setenforce: SELinux is disabled
✔ Passed: SELinux has been set to disabled. Please reboot the system for the changes to take effect.
ℹ Info: Download version file from https://public.eolinker.com/apipark/version.json...


────────────────────────────────────────────────────────────
? Question: Hello, Welcome to use APIPark! What do you want to do?
➜ Point: 1. Install APIPark
➜ Point: 2. Print system information
➜ Point: 3. Uninstall APIPark
➜ Point: 4. Exit
1
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
软件包 yum-utils-1.1.31-54.el7_8.noarch 已安装并且是最新版本
无须任何处理
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Index of /</title>
</head>
<body>
<h1>Index of /</h1>
<hr>
<pre>
<a href="linux">linux/</a>
<a href="mac">mac/</a>
<a href="win">win/</a>
</pre><hr></body></html>
已加载插件：fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] curl#35 - "TCP connection reset by peer"
Synchronizing system time...
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
软件包 ntp-4.2.6p5-29.el7.centos.2.x86_64 已安装并且是最新版本
无须任何处理
27 Sep 11:25:40 ntpdate[8310]: adjust time server 119.28.230.190 offset 0.404755 sec
setenforce: SELinux is disabled
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
软件包 epel-release-7-14.noarch 已安装并且是最新版本
无须任何处理
ℹ Info: Writing LAN_IP=10.211.55.11 to /tmp/apipark/quickstart/environment/LAN_IP
ℹ Info: Writing EXTERNAL_IP=124.74.108.206 to /tmp/apipark/quickstart/environment/EXTERNAL_IP
ℹ Info: checking docker network...
✔ Passed: finish checking docker network...
ℹ Info: init docker network...
create network apipark-net with subnet 172.100.0.0/24 and gateway 172.100.0.1
c7c1d01e258c2752eb37e896e426d2276faf773ddd99a367e0b65eb21147214e
✔ Passed: init docker network success


────────────────────────────────────────────────────────────
? Question: Please select the program you want to install:
➜ Point: 1. APIPark Dashboard and Node (API Gateway)
➜ Point: 2. Only APIPark Dashboard
➜ Point: 3. Only APIPark Node (API Gateway)
1
? Question: mysql.tar.gz already exists. Do you want to re-download package? (yes/no)
no
ℹ Info: Loading Docker image from mysql.tar.gz...
ℹ Info: Loaded image: docker.eolinker.com/basic/mysql:8.0.37
ℹ Info: Tagging image docker.eolinker.com/basic/mysql:8.0.37 as mysql:8.0.37...
✔ Passed: Successfully tagged image as mysql:8.0.37.
cfddfef10d1f3654921872628a603fccd1f0ea3de42ed2bcc4989301a2472c1c
docker exec -i apipark-mysql mysqladmin -u root -p123456 ping
⏳ Waiting: Waiting for MySQL to start...
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
✔ Passed: MySQL has been installed successfully
ℹ Info: Writing MYSQL_HOST=apipark-mysql to /tmp/apipark/quickstart/environment/MYSQL_HOST
ℹ Info: Writing MYSQL_PORT=3306 to /tmp/apipark/quickstart/environment/MYSQL_PORT
ℹ Info: Writing MYSQL_DATABASE=apipark to /tmp/apipark/quickstart/environment/MYSQL_DATABASE
ℹ Info: Writing MYSQL_USER=root to /tmp/apipark/quickstart/environment/MYSQL_USER
ℹ Info: Writing MYSQL_PASSWORD=123456 to /tmp/apipark/quickstart/environment/MYSQL_PASSWORD
ℹ Info: Writing MYSQL_EXPOSED_PORT=33306 to /tmp/apipark/quickstart/environment/MYSQL_EXPOSED_PORT
ℹ Info: Writing MYSQL_DATA_MOUNT=/var/lib/apipark/mysql to /tmp/apipark/quickstart/environment/MYSQL_DATA_MOUNT


────────────────────────────────────────────────────────────
? Question: redis.tar.gz already exists. Do you want to re-download package? (yes/no)
no
ℹ Info: Loading Docker image from redis.tar.gz...
ℹ Info: Loaded image: docker.eolinker.com/basic/cluster-redis:7.2.4
ℹ Info: Tagging image docker.eolinker.com/basic/cluster-redis:7.2.4 as redis:7.2.4...
✔ Passed: Successfully tagged image as redis:7.2.4.
17fd866e43015495a63ee4c91a54cb36b27218bdb01b324e526bf6622cfd9905
docker exec -i apipark-redis redis-cli ping
⏳ Waiting: Waiting for Redis to start...
NOAUTH Authentication required.

✔ Passed: Redis has been installed successfully
ℹ Info: Writing REDIS_HOST=apipark-redis to /tmp/apipark/quickstart/environment/REDIS_HOST
ℹ Info: Writing REDIS_PORT=6379 to /tmp/apipark/quickstart/environment/REDIS_PORT
ℹ Info: Writing REDIS_PASSWORD=123456 to /tmp/apipark/quickstart/environment/REDIS_PASSWORD
ℹ Info: Writing REDIS_EXPOSED_PORT=6379 to /tmp/apipark/quickstart/environment/REDIS_EXPOSED_PORT
ℹ Info: Writing REDIS_DATA_MOUNT= to /tmp/apipark/quickstart/environment/REDIS_DATA_MOUNT


────────────────────────────────────────────────────────────
ℹ Info: Check hardware conditions...
✔ Passed: Server configuration meets requirements. Proceeding with program execution.
? Question: influxdb.tar.gz already exists. Do you want to re-download package? (yes/no)
no
ℹ Info: Loading Docker image from influxdb.tar.gz...
ℹ Info: Loaded image: docker.eolinker.com/basic/influxdb:2.6
ℹ Info: Tagging image docker.eolinker.com/basic/influxdb:2.6 as influxdb:2.6...
✔ Passed: Successfully tagged image as influxdb:2.6.
ℹ Info: Installing InfluxDB...
b494ae3376a3a1183381acec54bebf23bd14f2b4e5c8fdfc97b6993c254ed652
docker exec -i apipark-influxdb influx version
⏳ Waiting: Waiting for InfluxDB to start...
Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z
✔ Passed: InfluxDB has been installed successfully
ℹ Info: Writing INFLUXDB_HOST=apipark-influxdb to /tmp/apipark/quickstart/environment/INFLUXDB_HOST
ℹ Info: Writing INFLUXDB_PORT=8086 to /tmp/apipark/quickstart/environment/INFLUXDB_PORT
ℹ Info: Writing INFLUXDB_EXPOSED_PORT=8086 to /tmp/apipark/quickstart/environment/INFLUXDB_EXPOSED_PORT


────────────────────────────────────────────────────────────
? Question: apipark.tar.gz already exists. Do you want to re-download package? (yes/no)
no
ℹ Info: Loading Docker image from apipark.tar.gz...
ℹ Info: Loaded image: apipark/apipark:v1.1.1-beta
ℹ Info: Tagging image apipark/apipark:v1.1.1-beta as apipark/apipark:v1.1.1-beta...
✔ Passed: Successfully tagged image as apipark/apipark:v1.1.1-beta.
e7cf4c2b3d9daa6f1971949362689f35d8d40a264774c2b5449dbb0ecbb192cb
ℹ Info: Writing APIPARK_CONSOLE_PORT=8288 to /tmp/apipark/quickstart/environment/APIPARK_CONSOLE_PORT
ℹ Info: Writing APIPARK_CONSOLE_EXPOSED_PORT=18288 to /tmp/apipark/quickstart/environment/APIPARK_CONSOLE_EXPOSED_PORT
ℹ Info: Writing APIPARK_CONSOLE_SUPPER_USER=admin to /tmp/apipark/quickstart/environment/APIPARK_CONSOLE_SUPPER_USER
ℹ Info: Writing APIPARK_CONSOLE_SUPPER_PASSWORD=iet8AhGo to /tmp/apipark/quickstart/environment/APIPARK_CONSOLE_SUPPER_PASSWORD
ℹ Info: Writing APIPARK_MOUNT= to /tmp/apipark/quickstart/environment/APIPARK_MOUNT
docker exec -i apipark curl -s -o /dev/null http://127.0.0.1:8288/api/v1/account/login
⏳ Waiting: Waiting for APIPark to start...
✔ Passed: APIPark has been installed successfully
✔ Passed: Install APIPark Dashboard success


────────────────────────────────────────────────────────────
? Question: apinto.tar.gz already exists. Do you want to re-download package? (yes/no)
no
ℹ Info: Loading Docker image from apinto.tar.gz...
ℹ Info: Loaded image: eolinker/apinto-gateway:0.17.7
ℹ Info: Tagging image eolinker/apinto-gateway:0.17.7 as eolinker/apinto-gateway:v0.17.7...
✔ Passed: Successfully tagged image as eolinker/apinto-gateway:v0.17.7.
ℹ Info: Installing APIPark Node (API Gateway)...
26e49f7479245a2c30fdc0e718c8f40cc4c2384db5f0518e77c8cb8ddfcb93e8
docker exec -i apipark-apinto curl -s -o /dev/null http://localhost:9400/api/router
⏳ Waiting: Waiting for Apinto to start...
✔ Passed: Apinto has been installed successfully
ℹ Info: Writing APINTO_ADMIN_PORT=9400 to /tmp/apipark/quickstart/environment/APINTO_ADMIN_PORT
ℹ Info: Writing APINTO_PROXY_PORT=8099 to /tmp/apipark/quickstart/environment/APINTO_PROXY_PORT
ℹ Info: Writing APINTO_PEER_PORT=9401 to /tmp/apipark/quickstart/environment/APINTO_PEER_PORT
ℹ Info: Writing APINTO_DATA_MOUNT=/var/lib/apipark/apinto to /tmp/apipark/quickstart/environment/APINTO_DATA_MOUNT
ℹ Info: Writing APINTO_LOG_MOUNT=/var/log/apipark/apinto to /tmp/apipark/quickstart/environment/APINTO_LOG_MOUNT
✔ Passed: Install APIPark Node (API Gateway) success


────────────────────────────────────────────────────────────
ℹ Info: Updating apipark node cluster...
ℹ Info: curl -s -i -H "Content-Type: application/json" -d "{"name":"admin","password":"iet8AhGo"}" http://10.211.55.11:18288/api/v1/account/login/username
✔ Passed: login success
ℹ Info: curl -s -X PUT -H "Cookie: session=59a7fff0-9c41-4a74-99c2-ae69c291580d" -d "{"manager_address":"10.211.55.11:9400"}" http://10.211.55.11:18288/api/v1/cluster/reset
✔ Passed: Update apipark node cluster successfully


────────────────────────────────────────────────────────────

░█████╗░██████╗░██╗██████╗░░█████╗░██████╗░██╗░░██╗
██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██╔══██╗██║░██╔╝
███████║██████╔╝██║██████╔╝███████║██████╔╝█████═╝░
██╔══██║██╔═══╝░██║██╔═══╝░██╔══██║██╔══██╗██╔═██╗░
██║░░██║██║░░░░░██║██║░░░░░██║░░██║██║░░██║██║░╚██╗
╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝
✔ Passed: InfluxDB has run successfully.
ℹ Info: The access information is as follows:
ℹ Info: Internal network access address: http://10.211.55.11:8086
ℹ Info: External network access address: http://124.74.108.206:8086

✔ Passed: APIPark Dashboard has run successfully.
ℹ Info: The access information is as follows:
ℹ Info: Internal network access address: http://10.211.55.11:18288
ℹ Info: External network access address: http://124.74.108.206:18288
ℹ Info: Username: admin
ℹ Info: Password: iet8AhGo

✔ Passed: APIPark Node (API Gateway) has run successfully. The access information is as follows:
ℹ Info: Admin API address: http://10.211.55.11:9400
ℹ Info: Proxy API Internal address: http://10.211.55.11:8099
ℹ Info: Proxy API External address: http://124.74.108.206:8099
ℹ Info: Peer API Internal address: http://10.211.55.11:9401
ℹ Info: Peer API External address: http://124.74.108.206:9401

**Comment by snycloud** [comment]
这两个问题，有没有什么方案可以临时解决，让我把流程走下去

**Comment by Dot-Liu** [comment]
请把上面那条信息删掉，这里有你服务器的信息，不建议展示在github
您加入我们的微信群，我群里和你沟通，并远程您看看
![image](https://github.com/user-attachments/assets/e6efeff8-ce0e-40b9-8ee0-828e94529dfe)

**Comment by snycloud** [comment]
> 请把上面那条信息删掉，这里有你服务器的信息，不建议展示在github 您加入我们的微信群，我群里和你沟通，并远程您看看 ![image](https://private-user-images.githubusercontent.com/14105999/371430654-e6efeff8-ce0e-40b9-8ee0-828e94529dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjEyNDYsIm5iZiI6MTcyNzQyMDk0NiwicGF0aCI6Ii8xNDEwNTk5OS8zNzE0MzA2NTQtZTZlZmVmZjgtY2UwZS00MGI5LThlZTAtODI4ZTk0NTI5ZGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZjUwMjUzNWUwYTI0ODc5NDQ2Zjg2NDBlZTkxNjI1OWJlYTlhMDk0OGEwMWIwNDkxYjY1MzFiYTBjYmRjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gx8tQqL8HRPfsSTbAuAjY1xkW1RNiFD0cuxey9aisuw)

好的，谢谢，已加入微信群，群里我找哪位沟通

**Comment by Dot-Liu** [comment]
> > 请把上面那条信息删掉，这里有你服务器的信息，不建议展示在github 您加入我们的微信群，我群里和你沟通，并远程您看看 ![image](https://private-user-images.githubusercontent.com/14105999/371430654-e6efeff8-ce0e-40b9-8ee0-828e94529dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjEyNDYsIm5iZiI6MTcyNzQyMDk0NiwicGF0aCI6Ii8xNDEwNTk5OS8zNzE0MzA2NTQtZTZlZmVmZjgtY2UwZS00MGI5LThlZTAtODI4ZTk0NTI5ZGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZjUwMjUzNWUwYTI0ODc5NDQ2Zjg2NDBlZTkxNjI1OWJlYTlhMDk0OGEwMWIwNDkxYjY1MzFiYTBjYmRjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gx8tQqL8HRPfsSTbAuAjY1xkW1RNiFD0cuxey9aisuw)
> 
> 好的，谢谢，已加入微信群，群里我找哪位沟通

该问题已解决，原因是admin不是该团队的团队管理员角色

**Comment by snycloud** [comment]
感谢大佬帮忙调试解决问题，有几点建议，看能否考虑：
1. 部署方式，建议能有 docker-compose 部署方式
2. 添加成员建议可以设置首次登录密码，并强制用户首次登录必须重置密码

**Comment by rolealiu** [comment]
> 感谢大佬帮忙调试解决问题，有几点建议，看能否考虑：
> 
> 1. 部署方式，建议能有 docker-compose 部署方式
> 2. 添加成员建议可以设置首次登录密码，并强制用户首次登录必须重置密码

感谢建议，后续会增加更多部署方式。
首次登陆密码目前还不是必要需求，我们先记录下来。

再次感谢👍
